### ISSUE TITLE
Friends example is not working as expected

### ISSUE THREAD

**Issue by devrz45** [lab-v2/pyreason#1]
I ran the example as  shown in the read me file, but the output that I got is:

`Filtering data...

 TIMESTEP - 0
  component    popular
0      Mary  [1.0,1.0]

 TIMESTEP - 1
  component    popular
0      Mary  [1.0,1.0]

 TIMESTEP - 2
  component    popular
0      Mary  [1.0,1.0]
`

The command that I ran was the following:

`python3 -m pyreason.scripts.diffuse --graph_path pyreason/examples/example_graph/friends.graphml --timesteps 2 --rules_yaml_path docs/hello-world/rules.yaml --facts_yaml_path docs/hello-world/facts.yaml --labels_yaml_path docs/hello-world/labels.yaml --ipl docs/hello-world/ipl.yaml --filter_label popular`

**Comment by dyumanaditya** [comment]
Hello @devrz45, Thank you for opening this issue.

The bug has been fixed as of 1828fa8f0a83a59eaa945c6219822395d17f6388
