### ISSUE TITLE
Expose YAML object class in SDK

### ISSUE THREAD

**Issue by buddha314** [lab-v2/pyreason#10]
Feature Request

While using the Python SDK, it would be useful to construct the `fact.yaml`, `rules.yaml` etc programmatically. If these are translated into classes, perhaps expose that class and allow `pr.load_rules(R)` where `R = pr.RulesClass()`

**Comment by dyumanaditya** [comment]
Thanks again @buddha314 we'll get this working soon too

**Comment by buddha314** [comment]
Are there code examples for this functionality?
