### ISSUE TITLE
Hello world error

### ISSUE THREAD

**Issue by funfwo** [lab-v2/pyreason#48]
It seems that numba does not operate as wanted. 
Thanks

![screenshot-1713841340512](https://github.com/lab-v2/pyreason/assets/462304/f5e07ef1-a226-4cdf-85ab-871d0338c168)
![screenshot-1713841363421](https://github.com/lab-v2/pyreason/assets/462304/11d1a341-c680-46c3-808e-281b8d7eeb40)
![screenshot-1713841388857](https://github.com/lab-v2/pyreason/assets/462304/e41c6471-4765-4e2e-b7f2-06ade5026b7b)

**Comment by dyumanaditya** [comment]
Hi @funfwo what version of python and numba are you using? Can you try with python 3.9 and numba 0.59.1?

**Comment by funfwo** [comment]
> Hi @funfwo what version of python and numba are you using? Can you try with python 3.9 and numba 0.59.1?

I tried python3.9 and python3.10 but problems occur in both context.

From the problem reference, may the default parameters initialization of reason class related to numba be the point.

**Comment by dyumanaditya** [comment]
Can you try running the code in a python file instead of a Jupyter notebook? Jupyter notebooks are currently not supported and can cause unwanted behaviour if cells are run multiple times without restarting the kernel.

**Comment by funfwo** [comment]
the number version is 0.59.1, as the requirements.txt indicates.
Problem is solved when the code is run in python terminal.
Thanks
