### ISSUE TITLE
Do we have an estimate on when this might be picked up or guidance on how can contribute.

### ISSUE THREAD

**Issue by KaminiAggarwal** [lab-v2/pyreason#50]
Do we have an estimate on when this might be picked up or guidance on how can contribute.

_Originally posted by @f-bdolan in https://github.com/lab-v2/pyreason/discussions/49#discussioncomment-9265408_

**Comment by dyumanaditya** [comment]
I don't have an exact timeline but I'm hoping it can be worked on in the next few months. The steps to make this possible are:

1. Make a `Threshold` class that contains information about one clause in a rule.
2. Currently a default "threshold" is being used [here](https://github.com/lab-v2/pyreason/blob/bf87f235aa39ffbb70dbda718f90b1851315d16a/pyreason/scripts/utils/rule_parser.py#L150) This has to be changed to take in a user specified threshold

**EXAMPLE:**
For a rule of the type:
`A customer is popular only if all the friends of a customer are popular.`

The rule would look like 
`popular(x) <- friends(x,y), popular(y)`

there would be two thresholds (corresponding to the two clauses):
1. `('greater_equal', ('number', 'total'), 1)` (there needs to be at least one friend for the first clause to be satisfied)
2. `('greater_equal', ('percent', 'total'), 100)` (100% of friends need to be popular for the second clause to be satisfied)

The `Threshold` class should be able to encode a threshold of the following format: `(quantifier, quantifier_type, thresh)`
where 
1. `quantifier` can be `greater_equal`, `greater`, `less_equal`, `less`, `equal`
2. `quantifier_type` is a tuple where: the first element can be either `number` or `percent` and the second element can be either `total` or `available`
3. `thresh` represents the numerical threshold value to compare against

**Comment by dyumanaditya** [comment]
Completed as of #51
