### ISSUE TITLE
Read Graph from NetworkX Graph object

### ISSUE THREAD

**Issue by buddha314** [lab-v2/pyreason#9]
Feature Request.

While using PyReason as a Python SDK, it would be useful to construct a NetworkX graph as an object programmatically, then pass that into the py engine.  

Allow both `pr.load_graph(path_to_graph)` and `pr.load_graph(G)` where `G = nx.Graph()` to avoid having to lay the XML to disk.

**Comment by dyumanaditya** [comment]
Thanks for this @buddha314. I agree this is important and user friendly, we'll open a PR soon.

**Comment by buddha314** [comment]
Excellent! is there a test or documentation where I can see the usage pattern?

**Comment by dyumanaditya** [comment]
@buddha314 see this [doc](https://github.com/lab-v2/pyreason/blob/main/docs/hello-world.md). The code associated with it is in the same folder. Hope this helps!
